// Generated by Wrangler on Wed Jul 17 2024 09:02:54 GMT+0000 (Coordinated Universal Time)
// by running `wrangler types`

interface Env {
    SPOTIFY_CLIENT_ID: string,
    SPOTIFY_CLIENT_SECRET: string
    REDIECT_URL: string,
}
